<h1 align="center"> 海洋数据分析 第五讲 </h1>
<h3 align="right">主讲人: 陈笔澄</h3>
<h2>目录<span class="tocSkip"></span></h2>
<div class="toc">
    <ul class="toc-item">
        <li> &nbsp;&nbsp; <font size=5>5. Python进阶知识--NumPy</li>
    </ul>
</div>

---

## 5. <font size=20>NumPy <img src="https://numpy.org/images/logo.svg" width=60>

## 官方手册: https://numpy.org/doc/stable/
- ### 可以查询到所有NumPy相关数据类型以及函数的具体信息

---

## ❓什么是Numpy

## 💡
- ### Numpy是Numerical Python的缩写。
- ### Python中科学计算的基础。
- ### 是各种复杂科学计算算法及数据结构模块(e.g., SciPy, Pandas)的基础。

---

## ❓Numpy的核心是什么

## 💡N维数组(array)及其处理能力。
- ### 关键词:数组
- ### 说明不是数组类型不适合使用NumPy

---

## ❓如何载入NumPy模块

In [1]:
import numpy # 最简单的方法
import numpy as np # 网上最常见的方法
from numpy import pi # 只需要载入部分功能时的方法

---

## ❓万里长征第一步: 如何创建一个NumPy数组

## 💡方法1: 运用Python列表(list)创建数组

In [2]:
# 1维数组
arr_1d = np.array([1, 2, 3, 4])
print(arr_1d)

[1 2 3 4]


In [3]:
# 2维数组
arr_2d = np.array([[11, 12, 13, 14], [21, 22, 23, 24]])
print(arr_2d)

[[11 12 13 14]
 [21 22 23 24]]


In [4]:
# 指定数据类型(与c语言类似)
arr_f64 = np.array([1, 2, 3, 4], dtype=np.float64)
print(arr_f64)

[1. 2. 3. 4.]


### 🔍 *常见错误: 缺少列表的中括号'[]'*，例如

In [5]:
arr_err = np.array(1, 2, 3, 4)

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

## 🔍 *重要技巧: 当出现错误是，仔细阅读错误信息能有效解决代码中的问题*

## ✏️练习: 如果列表能用于构建数组，那元组(tuple)、以及NumPy数组可以用于构建新数组吗？

In [ ]:
# 元组是否可以构建数组?
arr_tpl = 
# NumPy是否可以用于构建数组？
arr_arr = 

## 

## 💡方法2: 利用NumPy的内置函数

In [6]:
# 全0数组
arr_zero = np.zeros((4, 5)) # (4, 5)代表数组的纬度是4x5(4行5列)
print(arr_zero)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [7]:
# 全1数组
arr_one = np.ones((2, 3, 4), dtype=np.float32) # 内置函数一样可以指定类型
print(arr_one)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [8]:
# 无初始化数组
arr_emp = np.empty([3, 2]) # 注意初始值具有很强的不确定性
print(arr_emp)

[[4.67882019e-310 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]]


In [9]:
# 随机数组
arr_rand = np.random.rand(100)
print(arr_rand)
# numpy的random子模块有很多随机数生成函数，rand只是其中一个。

[0.18441468 0.6657246  0.6324988  0.60062042 0.27648542 0.3916279
 0.60006367 0.42050194 0.91593385 0.79551775 0.66897389 0.92473043
 0.79730304 0.15220735 0.77091307 0.00481359 0.57791695 0.56817689
 0.36996289 0.22455787 0.79651273 0.47855225 0.40320483 0.33713832
 0.58390194 0.25822085 0.49677439 0.27878258 0.71527251 0.79140565
 0.18731528 0.74955036 0.50915821 0.18057536 0.10433689 0.09472096
 0.25159909 0.14611283 0.87797212 0.88664401 0.44491164 0.75792548
 0.76526041 0.5221204  0.58549507 0.24610776 0.67141784 0.35392665
 0.40612851 0.25428329 0.61039525 0.51775923 0.85164016 0.03071871
 0.89215867 0.55532722 0.97330559 0.04600801 0.69264167 0.6060917
 0.34316691 0.23224481 0.65182122 0.80561698 0.67644611 0.51326409
 0.22994302 0.88514023 0.34215824 0.66262204 0.16961775 0.68169955
 0.21835529 0.59053461 0.9757044  0.58133486 0.05732008 0.68293467
 0.54595663 0.7687725  0.88202434 0.29465727 0.41081779 0.32982642
 0.32876164 0.26282815 0.45579265 0.98199821 0.67815596 0.754795

In [10]:
# 等差数列(类似于range类型，但含有数列所有值，且可为浮点型)
arr_ran = np.arange(1, 12.1, 0.5)
print(arr_ran)

[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10.  10.5 11.  11.5 12. ]


In [11]:
# 线性等分数列
arr_lin = np.linspace(0, 100, 11) # 1到100等间距分割为11个数
print(arr_lin)

[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


In [12]:
# 对数等分数列
arr_log = np.logspace(0, 10, 11) # 1e0到1e10按照对数指数等分为11个数
print(arr_log)

[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07 1.e+08 1.e+09
 1.e+10]


## 🔍NumPy初始化函数总结:
- ### `numpy.zeros(shape)`
- ### `numpy.ones(shape)`
- ### `numpy.empty(shape)`
- ### `numpy.random.rand(size)`
- ### `numpy.arange(start, end, span)`
- ### `numpy.linspace(start, end, size)`
- ### `numpy.logspace(start, end, size)`

---

## ❓既然是多维数组，我们怎么知道多维数组的纬度？

## 💡运用`numpy.shape`。

In [13]:
arr_nd = np.ones((5, 7, 4))
print(arr_nd.shape)

(5, 7, 4)


---

## ❓有了数组，我们该怎么提取数据

## 💡方法1: 与列表相似(但更复杂)的指数索引(indexing)与切片(slicing)索引。

### 📒回顾: 列表的指数索引与切片索引。

In [15]:
ls = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
#指数: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9

fmt = "{:20s}"
# 指数索引
print(fmt.format("指数索引 - ls[3]: "), ls[3])

# 切片索引
print(fmt.format("切片索引1 - ls[1:5]:"), ls[1:5])
print(fmt.format("切片索引2 - ls[1:5:2]:"), ls[1:5:2])
print(fmt.format("切片索引3 - ls[9:3:-3]"), ls[9:3:-3])
print(fmt.format("切片索引4 - ls[:4]:"), ls[:4])

指数索引 - ls[3]:        4
切片索引1 - ls[1:5]:     [2, 3, 4, 5]
切片索引2 - ls[1:5:2]:   [2, 4]
切片索引3 - ls[9:3:-3]   [10, 7]
切片索引4 - ls[:4]:      [1, 2, 3, 4]


In [16]:
# 开始前，先建立一个显示2维数组的函数
def show_2DArr(arr_2d, description):
    fmt = "{:4d}"
    print("{:s}:".format(description))
    for iy in range(arr_2d.shape[0]):
        for ix in range(arr_2d.shape[1]):
            print(fmt.format(arr_2d[iy, ix]), end='')
        print("")
    print("")
    return True

In [17]:
# 创建一个纬度为4x3的二维NumPy数组用于展示，多维数组方法类似。
arr_2d = np.array([[0, 1, 2, 3], [10, 11, 12, 13], [20, 21, 22, 23]])
# 显示原始数组
show_2DArr(arr_2d, "原始数组")

原始数组:
   0   1   2   3
  10  11  12  13
  20  21  22  23



True

In [18]:
fmt = "{:s}\n"
# 指数索引，只不过现在需要指定两个纬度。
print(fmt.format("指数索引 - arr_2d[2, 1]:"), arr_2d[2, 1])
# 指数索引现在可以是一个列表。
print(fmt.format("指数索引(列表) - arr_2d[[0, -1], [1, 3]]:"), arr_2d[[0, -1], [1, 3]])
# 切片索引，同理
print(fmt.format("切片索引 - arr_2d[:2, 2:]:"), arr_2d[:2, 2:])
# 混合索引
print(fmt.format("混合索引 - arr_2d[[0, -1], 1:]:"), arr_2d[[0, -1], 1:])

指数索引 - arr_2d[2, 1]:
 21
指数索引(列表) - arr_2d[[0, -1], [1, 3]]:
 [ 1 23]
切片索引 - arr_2d[:2, 2:]:
 [[ 2  3]
 [12 13]]
混合索引 - arr_2d[[0, -1], 1:]:
 [[ 1  2  3]
 [21 22 23]]


## ✏️练习: 下面的子数列对应的数值是多少？

In [ ]:
print(arr_2d[-1::-1, :])
print(arr_2d[[2, 0, 1], [3, 3, 1]])

## 

## 💡方法2: 条件运算

In [19]:
# 创建一个纬度为4x3的二维NumPy数组用于展示:
arr_2d = np.array([[0, 1, 2, 3], [10, 11, 12, 13], [20, 21, 22, 23]])
show_2DArr(arr_2d, "原始数组")

# 创新一个相同纬度的逻辑类型矩阵:
con_2d = np.array([[True, True, False, False], [False, True, False, False], [False, True, True, False]])
show_2DArr(con_2d, "条件数组")

selected_values = arr_2d[con_2d]
print("选择结果:", selected_values)

原始数组:
   0   1   2   3
  10  11  12  13
  20  21  22  23

条件数组:
   1   1   0   0
   0   1   0   0
   0   1   1   0

选择结果: [ 0  1 11 21 22]


In [150]:
# 选择符合条件的元素，例如
print(arr_2d[arr_2d<15])

[ 0  1  2  3 10 11 12 13]


---

## ❓可否改变多维数组的纬度

## 💡使用NumPy内置函数:

In [185]:
# 一样的原始数组
arr_2d = np.array([[0, 1, 2, 3], [10, 11, 12, 13], [20, 21, 22, 23]])
show_2DArr(arr_2d, "原始数组")

原始数组:
   0   1   2   3
  10  11  12  13
  20  21  22  23



True

In [70]:
# 将数组变为1维
arr1 = arr_2d.ravel() # ravel返回仍是原数组
arr2 = arr_2d.flatten() # flatten返回的是原数组的复制体
print(arr1)
print(arr2)

[ 0  1  2  3 10 11 12 13 20 21 22 23]
[ 0  1  2  3 10 11 12 13 20 21 22 23]


In [21]:
# 重新定义数组纬度
arr3 = arr_2d.reshape((2, 3, 2)) # reshape生成新数组
print(arr3)

print("")

arr3.resize((4, 3)) # resize直接改变原数组
print(arr3)

[[[ 0  1]
  [ 2  3]
  [10 11]]

 [[12 13]
  [20 21]
  [22 23]]]

[[ 0  1  2]
 [ 3 10 11]
 [12 13 20]
 [21 22 23]]


In [22]:
# 矩阵转置
arr4 = arr_2d.T
print(arr4)

[[ 0 10 20]
 [ 1 11 21]
 [ 2 12 22]
 [ 3 13 23]]


---

## ❓如何读写文件(如果不会读写文件，电脑关机怎么办)

## 💡方法1: 文本文件用`numpy.savetxt()`与`numpy.loadtxt()`处理

In [186]:
# 以practice4作业读取海洋数据举例

# 读取整个文件
data_ocean = np.loadtxt("./attachment/ocean_stat.txt", skiprows=1)
print(data_ocean[:5, :])

[[ 0.    17.956 24.227]
 [ 5.    17.996 24.277]
 [10.    17.996 24.233]
 [15.    17.996 24.056]
 [20.    18.099 23.525]]


In [79]:
# 读取指定列
data_ocean = np.loadtxt("./attachment/ocean_stat.txt", skiprows=1, usecols=[0, 2])
print(data_ocean[:5, :])

[[ 0.    24.227]
 [ 5.    24.277]
 [10.    24.233]]


In [23]:
# 将数据按格式写入文件
# 首先，恢复成原始数据
data_ocean = np.loadtxt("./attachment/ocean_stat.txt", skiprows=1)

# 写入文件
np.savetxt("./attachment/ocean_newstat.txt", data_ocean, fmt='%15.3e', delimiter=',',
    header='{:>15s}{:>15s}{:>15s}'.format('D (m)', 'T (DEG.C)', 'S (PSU)'))

## 

## 💡方法2: 直接使用NumPy对象进行读写(npy、npz格式)

In [25]:
# 以data_ocean为例，如何写入及读取NumPy对象文件。
data_ocean = np.loadtxt("./attachment/ocean_stat.txt", skiprows=1)

# 写入文件
np.save("./ocean_newstat.npy", data_ocean) # npy格式文件，非文本文件，无法直接观看

# 载入数据
data_newocean = np.load("./attachment/ocean_newstat.npy")
print(data_newocean[:5, :])

[[ 0.    17.956 24.227]
 [ 5.    17.996 24.277]
 [10.    17.996 24.233]
 [15.    17.996 24.056]
 [20.    18.099 23.525]]


In [26]:
# 万一有多个数组，使用numpy.savez()写入文件。
# 载入原始数据
data_ocean = np.load("./ocean_newstat.npy")

# 分解成三个数组
depth = data_ocean[:, 0]
temp = data_ocean[:, 1]
salt = data_ocean[:, 2]

# 存入npz文件
np.savez("./ocean_newstat.npz", depth=depth, temp=temp, salt=salt)

# 从npz文件中读取
data_newstat = np.load("./ocean_newstat.npz")
print(data_newstat['depth']) # 使用方法类似于字典

[  0.   5.  10.  15.  20.  25.  30.  35.  40.  45.  50.  55.  60.  65.
  70.  75.  80.  85.  90.  95. 100. 105. 110. 115. 120. 125. 130. 135.
 140. 145. 150.]


---

## ❓NumPy支持哪些运算

## 💡基本算数运算 (+, -, *, /, //, **, %)

In [106]:
data1 = np.array([1, 2])
data2 = np.ones((2, ))

print(data1 + data2)

[0. 0.]


## 

## 💡基础数列运算函数(`sum()`, `mean()`, `std()`, `min()`, `max()`)

In [27]:
data_ocean = np.load("./ocean_newstat.npy")

In [28]:
# 求和
sum_1 = np.sum(data_ocean) # 没有任何意义(里面包含了深度，温度，盐度；而不同的数据不能直接相加)
sum_2 = data_ocean.sum() # 一样没有任何意义
print(sum_1)
print(sum_2)

3461.4872000000005
3461.4872000000005


In [29]:
# 求平均值，避免平均不同的物理量，使结果有意义。
avg = data_ocean.mean(axis=0) # axis定义和函数在哪个纬度运算
print(avg)

[75.         19.06216129 17.59871613]


## 🔍注: 很多运算函数均存在内置函数(e.g., `arr.sum()`)与NumPy子函数(e.g., `numpy.sum()`)两个版本。

## 

## 💡扩展数列运算函数--只有想不到，没有做不到

In [138]:
x = np.arange(1, 11)
print("org x:", x)

# 平方
sqr = np.square(x)
print("\nsquare of x:", sqr)
# 平方根
sqrt = np.sqrt(x)
print("\nsquare root of x:", sqrt)
# e指数
exp = np.exp(x)
print("\nexponential of x:", exp)
# 对数
log = np.log(x)
print("\nln of x:", log)

org x: [ 1  2  3  4  5  6  7  8  9 10]

square of x: [  1   4   9  16  25  36  49  64  81 100]

square root of x: [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]

exponential of x: [2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04]

ln of x: [0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]


In [152]:
# 逻辑运算, 包含logical_and(), logical_or(), logical_xor(), logical_or
x = np.array([[True, True], [False, False]])
y = np.array([[True, False], [False, True]])
print(np.logical_and(x, y))

[[ True False]
 [False False]]


In [125]:
# 三角函数
x = np.linspace(0, 2*np.pi, 17)
sinx = np.sin(x)
print(sinx)
# 还有cos(), tan(); 反三角函数arcsin(), arccos(), arctan()等

[ 0.00000000e+00  3.82683432e-01  7.07106781e-01  9.23879533e-01
  1.00000000e+00  9.23879533e-01  7.07106781e-01  3.82683432e-01
  1.22464680e-16 -3.82683432e-01 -7.07106781e-01 -9.23879533e-01
 -1.00000000e+00 -9.23879533e-01 -7.07106781e-01 -3.82683432e-01
 -2.44929360e-16]


In [145]:
# 按条件赋值
x = np.random.randn(4, 3)
print("original:\n", x)
xwhere = np.where(x>=0.5, x, 0.5) # 如果>=0.5则维持原值，不然等于0.5
print("after where:\n", xwhere)

original:
 [[ 1.29086515  1.68560105 -0.73235382]
 [ 0.95801757  0.07443452  2.19704188]
 [ 0.75650273  1.10701467  0.28646796]
 [ 0.33123787 -0.81003545  1.52422321]]
after where:
 [[1.29086515 1.68560105 0.5       ]
 [0.95801757 0.5        2.19704188]
 [0.75650273 1.10701467 0.5       ]
 [0.5        0.5        1.52422321]]


array([1.29086515, 1.68560105, 0.95801757, 2.19704188, 0.75650273,
       1.10701467, 1.52422321])

In [146]:
# 定位: 寻找符合条件的元素索引指数，一般函数以arg开头
x = np.random.randn(4, 3)
print("original:\n", x)

# 寻找最大值索引指数
ind_max = np.argmax(x)
print("indices of max: ", ind_max) #以1维数组形式展示

# 同时还有argmin(), argwhere()等函数

original:
 [[-1.13994206 -0.40437169 -0.16791458]
 [ 1.29360189  0.87046904 -0.36033015]
 [ 1.7005083   0.89774046 -1.95153237]
 [ 0.67260023 -1.33322445 -0.64571876]]
indices of max:  6


# 🔍函数列表: https://numpy.org/doc/stable/reference/routines.math.html

---

## ❓相比于纯数值类型的List, 使用NumPy有什么优势

## 💡
- ### 丰富的功能
- ### 极高的计算效率 (作业题)

---

## 🔍注: 为了提升计算效率，NumPy数组的赋值很多时候是不创建新数组的。
## 这是双刃剑--要特别小心由此引发的灾难性后果!!!

In [31]:
arr_full = np.array([[0, 1, 2, 3], [10, 11, 12, 13], [20, 21, 22, 23]])
arr_part = arr_full[1:3, :] # arr_full的第一行以及第二行

In [32]:
print("arr_full:\n", arr_full)
print("arr_part:\n", arr_part)

arr_full:
 [[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]]
arr_part:
 [[10 11 12 13]
 [20 21 22 23]]


In [33]:
arr_part[:, :] = 0
print("arr_full:\n", arr_full)

arr_full:
 [[0 1 2 3]
 [0 0 0 0]
 [0 0 0 0]]


### 改变arr_part导致arr_full的值改变了。。。

## 🔍注: 当新数组需要与原数组独立存在时，保险起见，请使用内置函数`copy()`。

In [34]:
arr_full = np.array([[0, 1, 2, 3], [10, 11, 12, 13], [20, 21, 22, 23]])
arr_part = arr_full[1:3, :].copy() # 使用copy()函数
arr_part[:, :] = 0
print("arr_full:\n", arr_full) # 不会改变原数组的值

arr_full:
 [[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]]
